### ISSUE TITLE
Crea un setter. Para esto son

### ISSUE THREAD

**Issue by lmagarin** [AntonioGGdev/Programacion#1]
https://github.com/AntonioGGdev/Programacion/blob/8f81b6dc095eb591c97618c90c7cb11bfa604b3b/GESTISIMAL/Articulo.java#L25

**Comment by AntonioGGdev** [comment]
No se a que te refieres con esto, me lo podrías explicar algo más? Gracias

**Comment by lmagarin** [comment]
crea setUnidades.
Ahí se lanzará una excepción. 
Míralo en el foro. Hay algo parecido

**Comment by AntonioGGdev** [comment]
https://github.com/iesgrancapitan-programacion/gestisimal-AntonioGGdev/blob/848b6c64a675de07c315947b61513c1687024e38/Articulo.java#L55 ese es el setter que tengo para esto

**Comment by AntonioGGdev** [comment]
https://github.com/iesgrancapitan-programacion/gestisimal-AntonioGGdev/blob/17af7c6c061851109bb554b23027275eb8231ae4/Articulo.java#L50 creo que es eso
