### ISSUE TITLE
La comunicación con el usuario tiene que ir fuera. Lanza una excepción con el mensaje y lo capturas fuera en el Test

### ISSUE THREAD

**Issue by lmagarin** [AntonioGGdev/Programacion#11]
https://github.com/AntonioGGdev/Programacion/blob/8f81b6dc095eb591c97618c90c7cb11bfa604b3b/GESTISIMAL/Articulo.java#L71

**Comment by AntonioGGdev** [comment]
Ya tengo la excepción con el mensaje, pero no sé como capturarlo fuera en el test, lo capturo en el propio setter que es donde se lanza la excepción

**Comment by AntonioGGdev** [comment]
Cierro estos issues porque son de un repositorio erroneo.
