### ISSUE TITLE
Estas dos variables no tienen sentido en el estado del almacén. Con sólo el ArrayList es necesario

### ISSUE THREAD

**Issue by lmagarin** [AntonioGGdev/Programacion#12]
https://github.com/AntonioGGdev/Programacion/blob/8f81b6dc095eb591c97618c90c7cb11bfa604b3b/GESTISIMAL/Almacen.java#L16

Por favor, intenta entender el código de concesionario

**Comment by AntonioGGdev** [comment]
La variable unidadesActuales sirve para hacer el programa más legible y la variable i para todos los for que hay en los métodos.
