### ISSUE TITLE
Sobran los for. Usa los métodos de ArrayList

### ISSUE THREAD

**Issue by lmagarin** [AntonioGGdev/Programacion#13]
https://github.com/AntonioGGdev/Programacion/blob/8f81b6dc095eb591c97618c90c7cb11bfa604b3b/GESTISIMAL/Almacen.java#L41
Lee el enunciado y revisa el código que se os pasó

**Comment by AntonioGGdev** [comment]
Eliminados todos los for, he utilizado los métodos del arraylist y borrado las variables innecesarias nombradas en otro issue
