### ISSUE TITLE
Quita toda la comunicación del usuario y ponla en el test

### ISSUE THREAD

**Issue by lmagarin** [AntonioGGdev/Programacion#14]
https://github.com/AntonioGGdev/Programacion/blob/8f81b6dc095eb591c97618c90c7cb11bfa604b3b/GESTISIMAL/Almacen.java#L88
Revisa el material entregado

**Comment by AntonioGGdev** [comment]
Quitada total comunicación con el usuario fuera del test

**Comment by lmagarin** [comment]
Hola Antonio. Veo que cierras los issues pero no asocias el código en el commit.
Sé que lo habéis hecho con Jaime. 
https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords
De esa forma no tienes que comentar al cerrarlo. Directamente veo el código y lo cierras de forma automática
Procura hacerlo así la próxima vez

**Comment by lmagarin** [comment]
Además, cada vez que quiero acceder al master me da un 404. Cuando envíes el nuevo repositorio sigo corrigiéndotelo.

**Comment by AntonioGGdev** [comment]
Ya envié el nuevo repositorio varias veces, tanto a la entrega como a tí
por mensaje privado, revísalo cuando puedas
