### ISSUE TITLE
Capa de presentación??

### ISSUE THREAD

**Issue by lmagarin** [AntonioGGdev/Programacion#4]
https://github.com/AntonioGGdev/Programacion/blob/8f81b6dc095eb591c97618c90c7cb11bfa604b3b/GESTISIMAL/Articulo.java#L31
Capa de presentación??
Sólo en la capa de presentación puede haber comunicación con el usuario. Aquí ni println ni Teclado
https://es.wikipedia.org/wiki/Programaci%C3%B3n_por_capas

**Comment by AntonioGGdev** [comment]
Ya no hay comunicacion con el usuario en articulo.

**Comment by lmagarin** [comment]
Antonio. No cierras correctamente los issues. 
Además, necisito me envíes UN REPOSITORIO CON SÓLO GESTISIMAL.
Reenvíamelo

**Comment by AntonioGGdev** [comment]
https://github.com/iesgrancapitan-programacion/gestisimal-AntonioGGdev
