### ISSUE TITLE
La capturarás donde quieras mostrar el mensaje... en el Test. No puedes crear Un artículo con las unidades negativas

### ISSUE THREAD

**Issue by lmagarin** [AntonioGGdev/Programacion#5]
https://github.com/AntonioGGdev/Programacion/blob/8f81b6dc095eb591c97618c90c7cb11bfa604b3b/GESTISIMAL/Articulo.java#L30

**Comment by AntonioGGdev** [comment]
No se puede crear un artículo con las unidades negativas ya salta la excepción bien.
