### ISSUE TITLE
Revisa getters/setters. Ponlos todos privados y elimina los innecesarios. 

### ISSUE THREAD

**Issue by lmagarin** [AntonioGGdev/Programacion#6]
https://github.com/AntonioGGdev/Programacion/blob/8f81b6dc095eb591c97618c90c7cb11bfa604b3b/GESTISIMAL/Articulo.java#L47
En la POO el encapsulamiento es importante. Cada clase se encarga de lo suyo (ley de Demetrio), y en la medida de lo posible, métodos y sobre todo atributos han de ser private. 
Si otros programadores usan tu clase, debes asegurarte de que no puedan ocurrir errores por mal uso. Los niveles de acceso pueden ayudarlo a hacer esto.
[https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html](https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html)

Utiliza el nivel de acceso más restrictivo que tenga sentido en cada caso. Usa private a menos que tenga una buena razón para no hacerlo.
Evite los campos públicos excepto las constantes.

**Comment by AntonioGGdev** [comment]
borrados los getters/setters innecesarios y no se pueden poner privados, porque entonces no se podría acceder a ellos desde la clase Almacen.java
