### ISSUE TITLE
Crea una Excepción propia que herede de exception

### ISSUE THREAD

**Issue by lmagarin** [AntonioGGdev/Programacion#9]
https://github.com/AntonioGGdev/Programacion/blob/8f81b6dc095eb591c97618c90c7cb11bfa604b3b/GESTISIMAL/Articulo.java#L27

**Comment by AntonioGGdev** [comment]
Creada. [](https://github.com/iesgrancapitan-programacion/gestisimal-AntonioGGdev/blob/master/excepciones/UnidadesNegativasException.java)
